name: Build and test

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - main

# Permissions for the 'Publish test results' action
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and test solution
        uses: ./.github/actions/build-and-test-solution

      - name: Publish test results
        if: matrix.os == 'ubuntu-latest'
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            test-results/**/*.trx
